"""Generate an exact, recursive dependency lock from the active Python environment."""

from __future__ import annotations

import importlib.metadata
from pathlib import Path

from packaging.requirements import Requirement


ROOTS = ("crawl4ai", "openai", "python-dotenv", "langgraph", "httpx", "streamlit")
PROJECT_ROOT = Path(__file__).resolve().parents[1]


def canonical(name: str) -> str:
    return name.lower().replace("_", "-").replace(".", "-")


def main() -> None:
    distributions = {
        canonical(item.metadata["Name"]): item for item in importlib.metadata.distributions()
    }
    pending = [canonical(name) for name in ROOTS]
    selected: dict[str, importlib.metadata.Distribution] = {}
    while pending:
        name = pending.pop()
        if name in selected:
            continue
        distribution = distributions.get(name)
        if distribution is None:
            raise RuntimeError(f"活动环境缺少依赖：{name}")
        selected[name] = distribution
        for raw_requirement in distribution.requires or []:
            requirement = Requirement(raw_requirement)
            if requirement.marker and not requirement.marker.evaluate():
                continue
            pending.append(canonical(requirement.name))

    lines = [
        "# Generated by tools/generate_requirements_lock.py from the validated environment.",
        "# Regenerate after intentionally upgrading a direct dependency.",
    ]
    for name, distribution in sorted(selected.items()):
        lines.append(f"{distribution.metadata['Name']}=={distribution.version}")
    (PROJECT_ROOT / "requirements.lock").write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
